// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.1
// source: user.proto

/* eslint-disable */

export const protobufPackage = 'user';

/** Profile entity */
export interface Profile {
  id: number;
  displayName: string;
  avatarUrl: string;
  bio: string;
  createdAt: Date | undefined;
  updatedAt: Date | undefined;
}

/** User entity (TUser) */
export interface User {
  id: number;
  email: string;
  password: string;
  /** AppRole enum as string */
  role: string;
  createdAt: Date | undefined;
}

/** User with Profile (TUserWithProfile) */
export interface UserWithProfile {
  user: User | undefined;
  /** optional, can be null */
  profile: Profile | undefined;
}

export interface FindUsersForGlobalSearchRequest {
  ids: number[];
  selfUserId: number;
  limit: number;
}

export interface FindUsersForGlobalSearchResponse {
  users: UserWithProfile[];
}

export interface UserService {
  FindUsersForGlobalSearch(
    request: FindUsersForGlobalSearchRequest,
  ): Promise<FindUsersForGlobalSearchResponse>;
}
