export enum ESyncDataToESMessages {
  MESSAGE_MAPPINGS_NOT_FOUND = 'Message mappings not found',
  MESSAGE_ENCRYPTOR_NOT_SET = 'Message encryptor not set',
  SYNC_MESSAGE_ERROR = 'Sync message error',
  SYNC_USER_ERROR = 'Sync user error',
  SYNC_PROFILE_ERROR = 'Sync profile error',
  SYNC_DIRECT_CHAT_ERROR = 'Sync direct chat error',
  ES_PING_ERROR = 'Elasticsearch ping failed',
  SYNC_ES_CONNECTION_ERROR = 'Elasticsearch connection error',
  SYNC_MESSAGE_ENCRYPTOR_NOT_FOUND = 'Message encryptor not found',
  MESSAGE_MAPPING_NOT_FOUND = 'Message mapping not found',
  GROUP_CHAT_NOT_FOUND = 'Group chat not found',
  ES_MESSAGE_ENCRYPTOR_NOT_FOUND = 'Elasticsearch message encryptor not found',
  FAILED_TO_CREATE_MESSAGE_MAPPINGS = 'Failed to create message mappings',
}
