export enum EGroupChatMessages {
  MEMBER_NOT_FOUND = 'Member not found',
  FAILED_TO_UPDATE_GROUP_CHAT_AVATAR = 'Failed to update group chat avatar',
  GROUP_CHAT_NOT_FOUND_OR_NOT_A_MEMBER = 'Group chat not found or you are not a member of this group chat',
  FAILED_TO_CREATE_GROUP_CHAT = 'Failed to create group chat',
  YOU_DO_NOT_HAVE_PERMISSION_TO_CREATE_INVITE_LINK = 'You do not have permission to create invite link',
  INVALID_INVITE_LINK = 'Invalid invite link',
  GROUP_CHAT_NOT_FOUND = 'Group chat not found',
  USER_ALREADY_IN_GROUP_CHAT = 'User already in the group chat',
  GROUP_CHAT_PERMISSION_NOT_FOUND = 'Group chat permission not found',
  USER_HAS_NO_PERMISSION_UPDATE_GROUP_CHAT = 'User has no permission to update group chat',
  USER_ALREADY_HAS_REQUESTED_TO_JOIN_GROUP = 'User already has requested to join group before',
  GROUP_NAME_TOO_SHORT = 'Group name must be at least 2 characters',
  GROUP_MEMBERS_TOO_FEW = 'Group must have at least 2 members',
}
