// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.1
// source: auth.proto

/* eslint-disable */

export const protobufPackage = 'auth';

export interface LoginUserRequest {
  email: string;
  password: string;
}

export interface LoginUserResponse {
  success: boolean;
  token: string;
}

export interface LoginAdminRequest {
  email: string;
  password: string;
}

export interface LoginAdminResponse {
  success: boolean;
  token: string;
}

export interface CheckAdminEmailRequest {
  email: string;
}

export interface CheckAdminEmailResponse {
  isAdmin: boolean;
  message: string;
}

export interface CheckUserBanStatusRequest {
  userId: number;
}

export interface BanStatus {
  isBanned: boolean;
  banType: string;
  banReason: string;
  /** ISO datetime string */
  bannedUntil: string;
  message: string;
}

export interface CheckUserBanStatusResponse {
  banStatus: BanStatus | undefined;
}

export interface LogoutUserRequest {
  userId: number;
  socketId: string;
}

export interface LogoutUserResponse {
  success: boolean;
}

export interface AdminLogoutRequest {
  userId: number;
}

export interface AdminLogoutResponse {
  success: boolean;
}

export interface VerifyTokenRequest {
  token: string;
}

export interface VerifyTokenResponse {
  valid: boolean;
  /** full user info with profile */
  user: UserWithProfile | undefined;
  message: string;
}

export interface User {
  id: number;
  email: string;
  /** map với AppRole enum trong prisma */
  role: string;
  createdAt: Date | undefined;
}

export interface Profile {
  fullName: string;
  avatar: string;
  bio: string;
}

export interface UserWithProfile {
  user: User | undefined;
  profile: Profile | undefined;
}

export interface AuthService {
  LoginUser(request: LoginUserRequest): Promise<LoginUserResponse>;
  LoginAdmin(request: LoginAdminRequest): Promise<LoginAdminResponse>;
  CheckAdminEmail(
    request: CheckAdminEmailRequest,
  ): Promise<CheckAdminEmailResponse>;
  CheckUserBanStatus(
    request: CheckUserBanStatusRequest,
  ): Promise<CheckUserBanStatusResponse>;
  LogoutUser(request: LogoutUserRequest): Promise<LogoutUserResponse>;
  AdminLogout(request: AdminLogoutRequest): Promise<AdminLogoutResponse>;
  VerifyToken(request: VerifyTokenRequest): Promise<VerifyTokenResponse>;
}
